# Generated by Django 5.1.3 on 2024-11-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_leave_date_from_leaverequest_leave_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_date',
        ),
    ]
