# Generated by Django 5.1.3 on 2024-11-23 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_leaverequest_leave_days_and_more'),
    ]

    operations = [
       
    ]
