# Generated by Django 5.1.3 on 2024-11-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_leaverequest_application_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
