# Generated by Django 5.1.3 on 2024-11-23 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_leaverequest_leave_date'),
    ]

    operations = [
        
    ]
