# Generated by Django 5.1.3 on 2024-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_leaverequest_application_date_and_more'),
    ]

    operations = [
        
    ]
