# Generated by Django 5.1.3 on 2024-11-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_leaverequest_leave_days'),
    ]

    operations = [
        
    ]
