# Generated by Django 5.1.3 on 2024-12-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_leaveapplication_delete_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='whole_day',
        ),
    ]
